### ISSUE TITLE
Adhere awesome-go requirement to be added into its list

### ISSUE THREAD

**Issue by harunalfat** [Haraj-backend/hex-monscape#43]
By following [awesome-go](https://github.com/avelino/awesome-go) contribution [guidance](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md), we could gain larger exposure from people that'll be visiting its list if hex-monscape added into it.

First thing that I think should be prioritize is create link to the project's pkg.go.dev page

**Comment by riandyrn** [comment]
Is there any update regarding this issue, @harunalfat?

**Comment by harunalfat** [comment]
Since the last comment on [hex-monscape PR](https://github.com/avelino/awesome-go/pull/4935) from the repo owner, still no any update @riandyrn 

I'll wait till working day (Monday), if still no update, I'll try to message the repo owner
